### ISSUE TITLE
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory

### ISSUE THREAD

**Issue by roo-kie12** [bio-ontology-research-group/deepgo2#1]
According to README, I installed the dependencies, downloaded the data.tar.gz file and extracted it successfully. Then I follow the order, run the model with **python predict.py -if data/example.fa** ,but encountered an error: RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory.

Traceback (most recent call last):
  File "/data/home/jianglab/.conda/envs/deepgose/lib/python3.10/site-packages/esm/pretrained.py", line 33, in load_hub_workaround
    data = torch.hub.load_state_dict_from_url(url, progress=False, map_location="cpu")
  File "/data/home/jianglab/.conda/envs/deepgose/lib/python3.10/site-packages/torch/hub.py", line 750, in load_state_dict_from_url
    return torch.load(cached_file, map_location=map_location)
  File "/data/home/jianglab/.conda/envs/deepgose/lib/python3.10/site-packages/torch/serialization.py", line 797, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "/data/home/jianglab/.conda/envs/deepgose/lib/python3.10/site-packages/torch/serialization.py", line 283, in __init__
    super().__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/home/jianglab/deepgo2/predict.py", line 88, in <module>
    main()
  File "/data/home/jianglab/.conda/envs/deepgose/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/data/home/jianglab/.conda/envs/deepgose/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/data/home/jianglab/.conda/envs/deepgose/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/data/home/jianglab/.conda/envs/deepgose/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/data/home/jianglab/deepgo2/predict.py", line 33, in main
    proteins, data = extract_esm(in_file, out_file=out_file_esm, device=device)
  File "/data/home/jianglab/deepgo2/deepgo/extract_esm.py", line 60, in extract_esm
    model, alphabet = pretrained.load_model_and_alphabet(model_location)
  File "/data/home/jianglab/.conda/envs/deepgose/lib/python3.10/site-packages/esm/pretrained.py", line 28, in load_model_and_alphabet
    return load_model_and_alphabet_hub(model_name)
  File "/data/home/jianglab/.conda/envs/deepgose/lib/python3.10/site-packages/esm/pretrained.py", line 63, in load_model_and_alphabet_hub
    model_data, regression_data = _download_model_and_regression_data(model_name)
  File "/data/home/jianglab/.conda/envs/deepgose/lib/python3.10/site-packages/esm/pretrained.py", line 54, in _download_model_and_regression_data
    model_data = load_hub_workaround(url)
  File "/data/home/jianglab/.conda/envs/deepgose/lib/python3.10/site-packages/esm/pretrained.py", line 37, in load_hub_workaround
    data = torch.load(
  File "/data/home/jianglab/.conda/envs/deepgose/lib/python3.10/site-packages/torch/serialization.py", line 797, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "/data/home/jianglab/.conda/envs/deepgose/lib/python3.10/site-packages/torch/serialization.py", line 283, in __init__
    super().__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory

**Comment by coolmaksat** [comment]
Hello, it seems that something went wrong while downloading esm model. Could you please try to clean your TORCH_HOME and restart the script?

**Comment by roo-kie12** [comment]
> Hello, it seems that something went wrong while downloading esm model. Could you please try to clean your TORCH_HOME and restart the script?

Many thanks! In TORCH_HOME, I found the esm model was not downloaded in its entirely. I cleaned the TORCH_HOME and restarted the script, and It works now.
